const ACTIONS = {
    SET_SIDEBAR_VISIBILITY: "SET_SIDEBAR_VISIBILITY",
    SET_ADDFORM_VISIBILITY: "SET_ADDFORM_VISIBILITY",
    ADD_CHARACTER: "ADD_CHARACTER",
    DELETE_CHARACTER: "DELETE_CHARACTER",
};

export default ACTIONS;
